# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zrj-jcxlFdWUDsVUJlA2_VQ5upMEU8Sj
"""

# src/features/preprocessing.py

import pandas as pd
import numpy as np

def preprocess_data(df_train, df_test, target_column='Class', id_column='TransactionID'):
    """
    Pré-processa os dados para o treinamento do modelo.
    Inclui:
    - Separação de features e target.
    - Remoção de colunas de ID.
    - Alinhamento de colunas entre treino e teste.
    - Preenchimento de valores nulos com a mediana (calculada no treino).
    """
    df_train_processed = df_train.copy()
    df_test_processed = df_test.copy()

    # Armazenar labels e IDs
    train_labels = df_train_processed[target_column]
    train_ids = df_train_processed[id_column]
    test_ids = df_test_processed[id_column]

    # Remover colunas que não são features
    df_train_processed = df_train_processed.drop(columns=[target_column, id_column], errors='ignore')
    df_test_processed = df_test_processed.drop(columns=[id_column], errors='ignore')

    # Garantir que ambos os dataframes tenham as mesmas colunas
    # Se houver features categóricas, será necessário implementar one-hot encoding aqui
    # e depois alinhar as colunas (ex: usando df.align).
    # O código original assume que as colunas já são numéricas e alinháveis após a remoção de ID/target.
    common_cols = list(set(df_train_processed.columns) & set(df_test_processed.columns))
    df_train_processed = df_train_processed[common_cols]
    df_test_processed = df_test_processed[common_cols]

    # Preencher valores nulos com a mediana (calculada no conjunto de treino)
    # Importante: usar a mediana do treino para preencher tanto treino quanto teste para evitar vazamento de dados
    for col in df_train_processed.columns:
        if df_train_processed[col].isnull().any():
            median_val = df_train_processed[col].median()
            df_train_processed[col] = df_train_processed[col].fillna(median_val)
            df_test_processed[col] = df_test_processed[col].fillna(median_val)

    X = df_train_processed
    y = train_labels
    X_test = df_test_processed

    return X, y, X_test, train_ids, test_ids