# -*- coding: utf-8 -*-
"""data_loader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zrj-jcxlFdWUDsVUJlA2_VQ5upMEU8Sj
"""

# src/utils/data_loader.py

import pandas as pd
import os

def load_data(train_path='data/train.csv', test_path='data/test.csv'):
    """
    Carrega os datasets de treino e teste de paths especificados.
    Verifica a existência dos arquivos antes de carregar.
    """
    if not os.path.exists(train_path):
        raise FileNotFoundError(f"Arquivo de treino não encontrado em: {train_path}. Por favor, coloque 'train.csv' na pasta 'data'.")
    if not os.path.exists(test_path):
        raise FileNotFoundError(f"Arquivo de teste não encontrado em: {test_path}. Por favor, coloque 'test.csv' na pasta 'data'.")

    df_train = pd.read_csv(train_path)
    df_test = pd.read_csv(test_path)
    print("Dimensões do treino:", df_train.shape)
    print("Dimensões do teste:", df_test.shape)
    return df_train, df_test