# -*- coding: utf-8 -*-
"""eda.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zrj-jcxlFdWUDsVUJlA2_VQ5upMEU8Sj
"""

# src/utils/eda.py

import matplotlib.pyplot as plt
import seaborn as sns
import os

def explore_data(df, target_column='Class'):
    """
    Realiza uma exploração básica dos dados, incluindo:
    - head(), info(), describe()
    - Distribuição da coluna alvo
    - Valores nulos
    - Mapa de correlação
    Salva os gráficos na pasta 'results'.
    """
    print("\n--- Informações do DataFrame ---")
    print(df.head())
    print(df.info())
    print(df.describe())

    print(f"\n--- Distribuição da Coluna Alvo '{target_column}' ---")
    print(df[target_column].value_counts(normalize=True))

    # Plotar e salvar a distribuição das classes
    plt.figure(figsize=(6, 4))
    sns.countplot(x=target_column, data=df)
    plt.title(f'Distribuição das Classes (0 = Legítima, 1 = Fraude) - Coluna {target_column}')
    plt.tight_layout()
    os.makedirs('results', exist_ok=True) # Garante que a pasta results exista
    plt.savefig('results/class_distribution.png')
    plt.close()

    print("\n--- Valores Nulos ---")
    print(df.isnull().sum().sort_values(ascending=False))

    # Heatmap de correlação (para features numéricas)
    plt.figure(figsize=(12, 10))
    sns.heatmap(df.corr(numeric_only=True), annot=False, cmap='coolwarm')
    plt.title('Mapa de Correlação')
    plt.tight_layout()
    os.makedirs('results', exist_ok=True) # Garante que a pasta results exista
    plt.savefig('results/correlation_heatmap.png')
    plt.close()