# -*- coding: utf-8 -*-
"""submission_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zrj-jcxlFdWUDsVUJlA2_VQ5upMEU8Sj
"""

# src/utils/submission_generator.py

import pandas as pd
import os

def generate_submission(xgb_clf, X_test, test_ids, target_column='Class', output_path='results/submission.csv'):
    """
    Gera o arquivo de submissão no formato exigido pelo Kaggle.
    """
    print("\n--- Gerando Arquivo de Submissão ---")
    test_predictions = xgb_clf.predict_proba(X_test)[:, 1]

    submission = pd.DataFrame({
        'TransactionID': test_ids,
        target_column: test_predictions
    })
    os.makedirs('results', exist_ok=True) # Garante que a pasta results exista
    submission.to_csv(output_path, index=False)
    print(f"Arquivo '{output_path}' gerado com sucesso!")