# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zrj-jcxlFdWUDsVUJlA2_VQ5upMEU8Sj
"""

# src/main.py

# Importações dos módulos que criamos
from features.preprocessing import preprocess_data
from models.xgboost_model import train_model, evaluate_model
from utils.data_loader import load_data
from utils.eda import explore_data
from utils.submission import generate_submission

if __name__ == '__main__':
    print("Iniciando o pipeline de detecção de fraudes...")

    # 1. Carregar Dados
    # Certifique-se de que train.csv e test.csv estão na pasta 'data/'
    df_train, df_test = load_data()

    # 2. Explorar Dados (usando df_train para EDA)
    explore_data(df_train)

    # 3. Pré-processar Dados
    X, y, X_test_processed, train_ids, test_ids = preprocess_data(df_train, df_test)

    # 4. Treinar Modelo
    model, X_val, y_val = train_model(X, y)

    # 5. Avaliar Modelo
    evaluate_model(model, X_val, y_val)

    # 6. Gerar Submissão
    generate_submission(model, X_test_processed, test_ids)

    print("\nPipeline de detecção de fraudes concluído com sucesso!")